version: "3"

services:
  license-server:
    build:
      context: ./license_portal
    links:
      - postgres
    volumes:
      - ./license_portal:/app
    command: > #     wait 2 seconds for postgres to start
      sh -c "sleep 2 &&
      python3 manage.py migrate &&
      python3 manage.py runserver 0.0.0.0:8000"
    environment:
     POSTGRES_USER: 'admin'
     POSTGRES_PASSWORD: 'dummy_password'
     POSTGRES_DB: 'licenses'
     POSTGRES_HOST: 'postgres'
    depends_on:
      - postgres
    ports:
      - 8000:8000

  postgres:
    image: 'postgres:13'
    environment:
     POSTGRES_USER: 'admin'
     POSTGRES_PASSWORD: 'dummy_password'
     POSTGRES_DB: 'licenses'
     POSTGRES_HOST: 'postgres'
    ports:
      - 5432:5432

  redis:
    image: 'redis:alpine'
  celery:
    restart: always
    build:
      context: ./license_portal
    command: celery -A config.celery worker -l info
    volumes:
      - ./license_portal:/app
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'dummy_password'
      POSTGRES_DB: 'licenses'
      POSTGRES_HOST: 'postgres'
    depends_on:
      - postgres
      - redis
      - license-server