# Generated by Django 3.2 on 2022-08-15 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0002_auto_20220520_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='license_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'production'), (1, 'evaluation')]),
        ),
        migrations.AlterField(
            model_name='license',
            name='package',
            field=models.PositiveSmallIntegerField(choices=[(0, 'javascript_sdk'), (1, 'ios_sdk'), (2, 'android_sdk')]),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_body', models.TextField()),
                ('sent_datetime', models.DateTimeField(null=True)),
                ('sent', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='licenses.client')),
            ],
        ),
    ]
