# Generated by Django 3.2 on 2022-08-16 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0003_auto_20220816_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sent_to',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
